### ISSUE TITLE
Obsolete "helm-recoll-action-invoke-helm" function

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm-recoll#7]
@csantosb I removed the "helm-recoll-action-invoke-helm" action from the action list of the "helm-recoll-source" class because it seemingly doesn't belong there.  It more looks like an action for intended for "helm-recoll-sources-source" - and it looks a quite similar to an action specified there.

Could you please have a look if those two things can be merged?  Thanks in advance.

**Comment by csantosb** [comment]
>@csantosb I removed the "helm-recoll-action-invoke-helm" action from the action list of the "helm-recoll-source" class because it seemingly doesn't belong there.  It more looks like an action for intended for "helm-recoll-sources-source" - and it looks a quite similar to an action specified there.
>
>Could you please have a look if those two things can be merged?  Thanks in advance.

In fact, these two things provide different functionality, unfortunately, their
names are quite similar.

"Invoke helm with selected sources" lambda action calls helm with the source created by
"helm-recoll-create-source". That's fine. Once the previous source is selected,
the user limits candidates with a pattern to those where the
pattern appear inside the candidate (more advanced filtering is available too).

Then, selecting candidates with M-SPC (maybe all of them M-a), and calling
"helm-recoll-action-invoke-helm", a new helm instance is created with selected
candidates. Now, user may filter out candidates by its names, directories,
etc. This functionality is broken by your last commit.

I suggest renaming "helm-recoll-action-invoke-helm" to something else ("require"),
adding it to "helm--setup-source", and appending it to "helm-type-file-actions".
I prefer having fast access to it by just pressing enter, that's why I
pre-append.

Please, review PR #8.

**Comment by michael-heerdegen** [comment]
I understand the intention now, thanks for the explanation.  I agree it's useful.

OTOH, wouldn't it be even more useful if one could limit file names already from the recoll source session?

According to the help message, one should be able to use "-f" in the prompt to match file names, but I get an error message when I try to do that.

**Comment by csantosb** [comment]
>I understand the intention now, thanks for the explanation.  I agree it's useful.
>
>OTOH, wouldn't it be even more useful if one could limit file names already from the recoll source session?

Indeed you can with "filename: something" or dir: or ext:, etc. This works.
I just prefer my alternative as a faster solution.

Maybe we could append this action to the end in "helm--setup-source" and assign it
to a keystroke for fast access ? Just to avoid attaching it to "f1", which might
be too intrusive, specially if the user prefers not using it.

>According to the help message, one should be able to use "-f" in the prompt to match file names, but I get an error message when I try to do that.

I know, this is next to be fixed. Not a priority by now, as I am not using it.

**Comment by michael-heerdegen** [comment]
Ok, let me think about it.  I think about a better name than "require" though.

**Comment by michael-heerdegen** [comment]
Ok, let's keep it.  I made an issue for the non working switches.
